name: Run Datadog Synthetic tests

on: [push, pull_request]

jobs:
  run-synthetics-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Datadog Synthetic tests
        uses: DataDog/synthetics-ci-github-action@v2
        with:
          api_key: ${{ secrets.DD_API_KEY }}
          app_key: ${{ secrets.DD_APP_KEY }}
